---
subtitle: "Regression der Opferstatistik"
author: "D'Alessandro David"
date: "`r format(Sys.Date())`"
output:  html_document
bibliography: references.bib
csl: "https://www.zotero.org/styles/apa-with-abstract"
lang: de
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

# Kriminalitässtatistik
https://www.bka.de/DE/AktuelleInformationen/StatistikenLagebilder/PolizeilicheKriminalstatistik/PKS2021/PKSTabellen/KreisOpfertabellen/kreisOpfertabellen_node.html--> Kann verworfen werden

https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/04-kreise.html

https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/_inhalt.html# 

https://www.regionalstatistik.de/genesis/online?operation=statistic&levelindex=0&levelid=1685395020968&code=13111#abreadcrumb 

https://www.regionalstatistik.de/genesis/online?operation=abruftabelleBearbeiten&levelindex=2&levelid=1685395674289&auswahloperation=abruftabelleAuspraegungAuswaehlen&auswahlverzeichnis=ordnungsstruktur&auswahlziel=werteabruf&code=13111-02-02-4&auswahltext=&werteabruf=Werteabruf#abreadcrumb 

Bevölkerung in Gemeinde https://www.regionalstatistik.de/genesis//online?operation=table&code=12411-01-01-4&bypass=true&levelindex=1&levelid=1685395910046#abreadcrumb

Wahlstimmen-nicht sinnvoll
https://www.regionalstatistik.de/genesis/online?operation=statistic&levelindex=0&levelid=1685395020968&code=14338#abreadcrumb

Absolventen und Schulen
https://www.regionalstatistik.de/genesis/online?operation=statistic&levelindex=0&levelid=1685395020968&code=21111#abreadcrumb


##Datenbanken zu mehr inhalt: https://www.statistikportal.de/de/gesundheit#datenbanken
Regionalatlas Deutschland Themenbereich "Soziales" Indikatoren zu "Armutsgefährdung"
https://www.regionalstatistik.de/genesis/online?operation=abruftabelleBearbeiten&levelindex=0&levelid=1685530852339&auswahloperation=abruftabelleAuspraegungAuswaehlen&auswahlverzeichnis=ordnungsstruktur&auswahlziel=werteabruf&code=AI-S-02&auswahltext=&werteabruf=Werteabruf#abreadcrumb

https://www.statistikportal.de/de/arbeitsmarkt#datenbanken

https://www.regionalstatistik.de/genesis/online?language=de&sequenz=statistikTabellen&selectionname=23111#abreadcrumb

[Vgl. @Bankhofer.2008,S. 32]

## Arbeitnehmerentgelte in Kreisen
https://www.statistikportal.de/de/vgrdl/ergebnisse-kreisebene/einkommen-kreise
## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

